# Notes:
#  - you can skip a build by adding [ci skip] to the commit message 
#

# see http://about.travis-ci.org/docs/user/languages/php/
language: php

# test for these PHP versions and environments
php:
   - 5.5
   - 5.6
#   - 7.0

#env:
#   - DB=mysql


# only build these branches (RegEx is also valid, eg. /^deploy.*$/):
branches:
  only:
    - Backend-PHP-Stack
    - travisTest

before_install:
   - /home/travis/.phpenv/versions/5.5/bin/composer self-update

# skip installation step
install: true

#before_script:

# skip build
script: true

# use curl to deploy to our server
# $FTP_USER, $FTP_PASSWORD and $FTP_URL are enrypted env-variables
after_success:
   - "find Backend-PHP-Stack -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD $FTP_URL/test/{}"
#   - 'curl --ftp-create-dirs -T "Backend-PHP-Stack/config.inc.php" -u $FTP_USER:$FTP_PASSWORD "$FTP_URL/test/"'
#   - "curl --ftp-create-dirs -T Backend-PHP-Stack/index.php -u $FTP_USER:$FTP_PASSWORD $FTP_URL/test/"
#   - "curl --ftp-create-dirs -T Backend-PHP-Stack/webstart.inc.php -u $FTP_USER:$FTP_PASSWORD $FTP_URL/test/"
#   - "curl --ftp-create-dirs -T 'Backend-PHP-Stack/{config.inc.php,index.php,webstart.inc.php}' -u $FTP_USER:$FTP_PASSWORD $FTP_URL/test/"
#   - "curl --ftp-create-dirs -T 'Backend-PHP-Stack/class/{error_log.class.php,file.class.php,globalfunctions.function.php,message.class.php,message.class.php,picture_file.class.php,user.class.php,video_file.class.php}' -u $FTP_USER:$FTP_PASSWORD $FTP_URL/test/class/"
  
#after_failure:

#before_deploy:

# let travis skip the cleanup process after the build
#deploy:
#  skip_cleanup: true

#after_deploy:

#after_script: